import Head from 'next/head'
import { useSpringRef, useChain, useSpring, animated } from 'react-spring'
import styled from 'styled-components'
import Item1 from '../assets/svg/item1.svg'
import Item2 from '../assets/svg/item2.svg'
import Item3 from '../assets/svg/item3.svg'
import Item4 from '../assets/svg/item4.svg'

export default function Home() {

    // animated start
    const animatedHead = useSpring({
      from: { backgroundColor: '#fff' },
      to: { backgroundColor: '#f5f5f5' },
      duration: 1000,
    })

    const springRefTitle = useSpringRef()
    const animatedTitle = useSpring({
      from: { y: 10, opacity: 0 },
      to: { y: 0, opacity: 1 },
      ref: springRefTitle
    })

    const springRefDescription = useSpringRef()
    const animatedDescription = useSpring({
      from: { y: 10, opacity: 0 },
      to: { y: 0, opacity: 1 },
      ref: springRefDescription
    })

    useChain([springRefTitle, springRefDescription], [0, 0.3])

    const animatedItemLeft = useSpring({
      from: { x: -40, opacity: 0 },
      to: { x: 0, opacity: 1 },
    })
    const animatedItemRight = useSpring({
      from: { x: 40, opacity: 0 },
      to: { x: 0, opacity: 1 },
    })
    // animated end

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledHead style={{ ...animatedHead }}>
        <StyledHeadTitle style={{ ...animatedTitle }}>
          Welcome to <a href="">UCenter!</a>
        </StyledHeadTitle>

        <StyledHeadDescription style={{ ...animatedDescription }}>Get started</StyledHeadDescription>
      </StyledHead>

      <StyledItem>
        <StyledItemImg style={{ ...animatedItemLeft }} src={Item1} alt="illustration" />
        <StyledItemCard href="https://nextjs.org/docs" style={{ ...animatedItemRight }} >
          <h2>Documentation &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </StyledItemCard>
      </StyledItem>

      <StyledItem>
        <StyledItemCard style={{ ...animatedItemLeft }} href="https://nextjs.org/learn" >
          <h2>Learn &rarr;</h2>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </StyledItemCard>
        <StyledItemImg src={Item2} style={{ ...animatedItemRight }} alt="illustration" />
      </StyledItem>

      <StyledItem>
        <StyledItemImg style={{ ...animatedItemLeft }} src={Item3} alt="illustration" />
        <StyledItemCard
          style={{ ...animatedItemRight }}
          href="https://github.com/vercel/next.js/tree/master/examples"
        >
          <h2>Examples &rarr;</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </StyledItemCard>
      </StyledItem>

      <StyledItem>
        <StyledItemCard
          style={{ ...animatedItemLeft }}
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        >
          <h2>Deploy &rarr;</h2>
          <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
        </StyledItemCard>
        <StyledItemImg style={{ ...animatedItemRight }} src={Item4} alt="illustration" />
      </StyledItem>
      <StyledFooter>
          © 2021 Meta Network All Rights Served
      </StyledFooter>
    </>
  )
}

const StyledHead = styled(animated.section)`
  width: 100%;
  height: 600px;
  background-color: #f5f5f5;
  display: flex;
  flex-direction: column;
  justify-content: center;
`

const StyledHeadTitle = styled(animated.h1)`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;
  a {
    color: #0070f3;
    text-decoration: none;
  }
  a:hover,
  a:focus,
  a:active {
    text-decoration: underline;
  }
`
const StyledHeadDescription = styled(animated.p)`
  line-height: 1.5;
  font-size: 1.5rem;
  text-align: center;
`

const StyledItem = styled.section`
  max-width: 1400px;
  padding: 0 20px;
  margin: 200px auto;
  display: flex;
  justify-content: center;
  @media screen and (max-width: 768px) {
    flex-direction: column;
  }
  @media screen and (max-width: 576px) {
    padding: 0 10px;
  }
`
const StyledItemImg = styled(animated.img)`
  width: 500px;
  @media screen and (max-width: 768px) {
    width: 90%;
    margin: 0 auto;
  }
`
const StyledItemCard = styled(animated.a)`
  margin: 0;
  padding: 1.5rem 4rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border-radius: 10px;
`

const StyledFooter = styled.footer`
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
`